spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: wjdwpdlf7614@gmail.com
    password: jrrp fzog tjdc gwae
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
