spring:
  application:
    name: demo
  profiles:
    include: db, email
  thymeleaf:
    cache: false #thymeleaf 설정//
  mvc:
    static-path-pattern: "/static/**"
  #  prefix: classpath:/templates/   # .html 파일을 불러오기 위한 경로 설정(src/main/resources/templates)
  #  suffix: .html   # 파일 확장자
  #  cache: false #/static/**

logging:
  level:
    root: debug






devtools:
  livereload:
    enable: true

application:
  security:
    jwt:
      secret-key: D4A9C8F77E3F67459B1B43DCC67A20FB2A7D8A9E2D7A11E9F3F8B0AA1D7E0C42
      expiration: 86400000

server:
  servlet:
    encoding:
      force-response: true
  error:
    whitelabel:
      enabled: false